name: farmers
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Set up AWS CLI
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
          aws configure set aws_access_key_id $(cat aws_access_key_id)
          aws configure set aws_secret_access_key $(cat aws_secret_access_key)
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install dvc==3.23.0
          pip install -r requirements.txt
          dvc pull
          dvc repro 

          git fetch --prune
          dvc artifact/metrics diff --show-md master > report.md

          # Add figure to the report
          echo "## Validating results by region"
          cml-publish artifact/by_region.png --md >> report.md
          cml-send-comment report.md
