name: farmers
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10
        run: sudo apt-get install -y python3.10
        
      - name: Install pip
        run: |
          python -m pip install --upgrade pip

